server:
  port: 8130
# 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-openfeign
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        
#  openfeign整合sentinel
feign:
  sentinel:
    enabled: true
