# 数据源
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.162.130:3316/seata_stock?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #初始化时运行sql脚本
    schema: classpath:sql/schema.sql
    initialization-mode: never
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    alibaba:
      seata:
        tx-service-group: guangzhou
  application:
    name: stock-seata
#设置mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.dehu.order.stock
  configuration:
    mapUnderscoreToCamelCase: true
server:
  port: 8071
