server:
  port: 8051
# 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-nacos
  cloud:
    nacos:
      server-addr: 192.168.57.128:8847
      discovery:
        username: nacos
        password: nacos
    #将ribbon进行禁用，而使用springcloud中的loadbalancer
    loadbalancer:
      ribbon:
        enabled: false