server:
  port: 8061
# 应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-openfeign
  cloud:
    nacos:
      server-addr: 192.168.57.128:8847
      discovery:
        username: nacos
        password: nacos

#        cluster-name: qudehu
#        metadata: version=1 可以结合元数据进行扩展
#        weight: 通常要结合 安装 权重的负载均衡策略，权重越高则分配的流量越大
#        group: 可以对相同特征的服务进行分类分组管理
#        ephemeral: false 默认为true（临时实例），当服务宕机时，超过心跳，就会将实例进行剔除
#        永久实例，即使宕机了也不会删除实例，
#        namespace: public 可以对相同特征的服务进行归类分组管理

#        springboot的默认日志级别是info，feign的debug日志级别就不会输入
logging:
  level:
#   只对这个文件夹下的文件设置debug级别
    com.dehu.order.feign: debug
feign:
  client:
    config:
      product-nacos:
        loggerLevel: BASIC
        # 连接超时时间，默认2s
        connectTimeout: 5000
        # 请求处理超时时间，默认5s
        readTimeout: 10000
        contract: feign.Contract.Default # 修改product为默认的契约机制，（还原为feign原生的注解，一般使用配置文件的方式而非配置类的形式）
        request-interceptors:
          com.dehu.order.interceptor.feign.CustomFeignInterceptor
